# Generated by Django 4.2.10 on 2024-03-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_alter_fieldswork_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficiary Category')),
                ('action_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الإجراء')),
                ('place_implementation', models.CharField(blank=True, max_length=100, null=True, verbose_name=' Place Implementation')),
                ('number_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Number Unit')),
                ('cost_unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cost Unit')),
                ('date_implementation', models.DateTimeField(blank=True, null=True, verbose_name='Date Implementation')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='الإجمالي')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_organization', to='organizations.organization', verbose_name='Organization Implemented')),
            ],
            options={
                'verbose_name': 'Implemented project ',
                'verbose_name_plural': 'Implemented projects ',
            },
        ),
    ]
