# Generated by Django 4.2.10 on 2024-03-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='place_implementation',
        ),
        migrations.CreateModel(
            name='PlacesImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20, verbose_name='Name Place')),
                ('Number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number places')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_project', to='projects.project', verbose_name='Place Project')),
            ],
            options={
                'verbose_name': 'Place Implementation',
                'verbose_name_plural': 'Places Implementation',
            },
        ),
    ]
