# Generated by Django 4.2.10 on 2024-02-29 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='fieldswork',
            options={'verbose_name': 'Field of Work', 'verbose_name_plural': 'Fields of Work'},
        ),
        migrations.AlterModelOptions(
            name='headquartercountry',
            options={'verbose_name': 'Headquarter Country', 'verbose_name_plural': 'Headquarter Countries'},
        ),
        migrations.AlterModelOptions(
            name='organizations',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(max_length=150, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_country', to='organizations.organizations', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='fieldswork',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Field of Work'),
        ),
        migrations.AlterField(
            model_name='fieldswork',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_field_work', to='organizations.organizations', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='headquartercountry',
            name='country',
            field=models.CharField(max_length=150, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='headquartercountry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_Headquarter_country', to='organizations.organizations', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='number_phone',
            field=models.CharField(max_length=150, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='type_organization',
            field=models.CharField(max_length=150, verbose_name='Type of Organization'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='website',
            field=models.URLField(verbose_name='Website'),
        ),
    ]
