# Generated by Django 4.2.10 on 2024-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_countries_options_alter_fieldswork_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'الدولة', 'verbose_name_plural': 'الدول'},
        ),
        migrations.AlterModelOptions(
            name='fieldswork',
            options={'verbose_name': 'مجال عمل المؤسسة', 'verbose_name_plural': 'مجالات عمل المؤسسة'},
        ),
        migrations.AlterModelOptions(
            name='headquartercountry',
            options={'verbose_name': 'دولة المقر الرئيسي', 'verbose_name_plural': 'دول المقر الرئيسي'},
        ),
        migrations.AlterModelOptions(
            name='organizations',
            options={'verbose_name': 'المنظمة', 'verbose_name_plural': 'المنظمات'},
        ),
        migrations.RemoveField(
            model_name='countries',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='fieldswork',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='headquartercountry',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizations',
            name='countries',
            field=models.ManyToManyField(related_name='organization_country', to='organizations.countries', verbose_name='الدول'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='fieldswork',
            field=models.ManyToManyField(related_name='organization_fieldswork', to='organizations.fieldswork', verbose_name='Fields Work'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='headquartercountry',
            field=models.ManyToManyField(related_name='head_quarter_Country', to='organizations.headquartercountry', verbose_name='دولة المقر الرئيسي'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='job_title',
            field=models.CharField(default=' ', max_length=150, verbose_name='Job title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizations',
            name='name_person',
            field=models.CharField(default=' ', max_length=150, verbose_name='Name of responsible person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizations',
            name='number_whatsup',
            field=models.CharField(default=' ', max_length=150, verbose_name='Number Whats Up'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizations',
            name='password',
            field=models.CharField(default=' ', max_length=128, verbose_name='كلمة المرور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizations',
            name='username',
            field=models.CharField(default=' ', max_length=150, verbose_name='User Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(max_length=150, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='fieldswork',
            name='name',
            field=models.CharField(max_length=150, verbose_name='مجال عمل المؤسسة'),
        ),
        migrations.AlterField(
            model_name='headquartercountry',
            name='country',
            field=models.CharField(max_length=150, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='الايميل'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(max_length=150, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='number_phone',
            field=models.CharField(max_length=150, verbose_name='رفم الهاتف'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='type_organization',
            field=models.CharField(max_length=150, verbose_name='نوع المنظمة'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='website',
            field=models.URLField(verbose_name='الموقع'),
        ),
    ]
