# Generated by Django 4.2.10 on 2024-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_countries_options_alter_fieldswork_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='الايميل')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('otp', models.CharField(blank=True, max_length=100, null=True, verbose_name='OTP')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='Expire Date')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('type_organization', models.CharField(max_length=150, verbose_name='نوع المنظمة')),
                ('email', models.EmailField(max_length=150, verbose_name='الايميل')),
                ('number_phone', models.CharField(max_length=150, verbose_name='رفم الهاتف')),
                ('website', models.URLField(verbose_name='الموقع')),
                ('name_person', models.CharField(max_length=150, verbose_name='Name of responsible person')),
                ('job_title', models.CharField(max_length=150, verbose_name='Job title')),
                ('number_whatsup', models.CharField(max_length=150, verbose_name='Number Whats Up')),
                ('country', models.CharField(max_length=150, verbose_name='الدولة')),
            ],
            options={
                'verbose_name': 'المنظمة',
                'verbose_name_plural': 'المنظمات',
            },
        ),
        migrations.CreateModel(
            name='OrganizationActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=255, verbose_name='نوع الإجراء')),
                ('finished', models.FloatField(blank=True, null=True, verbose_name='تم الإنجاز')),
                ('finished_percentage', models.FloatField(blank=True, null=True, verbose_name='نسبة الإنجاز')),
            ],
            options={
                'verbose_name': 'Organization Action',
                'verbose_name_plural': 'Organizations Actions',
            },
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='fieldswork',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='headquartercountry',
        ),
        migrations.AlterModelOptions(
            name='fieldswork',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headquartercountry',
            options={},
        ),
        migrations.AlterField(
            model_name='fieldswork',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='headquartercountry',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
