# Generated by Django 4.2.10 on 2024-03-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_delete_organizations_organizationactions_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldswork',
            options={'verbose_name': 'مجالات عمل المؤسسة', 'verbose_name_plural': 'مجالات عمل المؤسسة'},
        ),
        migrations.AlterModelOptions(
            name='headquartercountry',
            options={'verbose_name': 'دولة المقر الرئيسي', 'verbose_name_plural': 'دولة المقر الرئيسي'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'الدعوات', 'verbose_name_plural': 'الدعوات'},
        ),
        migrations.AlterModelOptions(
            name='organizationactions',
            options={'verbose_name': 'إجراءات المنظمات', 'verbose_name_plural': 'إجراءات المنظمات'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='fields_work',
            field=models.ManyToManyField(related_name='organization_fieldswork', to='organizations.fieldswork', verbose_name='مجالات عمل المؤسسة'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='job_title',
            field=models.CharField(max_length=150, verbose_name='مسمى وظيفي'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_person',
            field=models.CharField(max_length=150, verbose_name='اسم الشخص المسؤول'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='number_whatsup',
            field=models.CharField(max_length=150, verbose_name='رقم الواتس اب'),
        ),
    ]
