# Generated by Django 4.2.10 on 2024-03-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_invitation_organization_organizationactions_and_more'),
        ('accounts', '0003_alter_profile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_organization', to='organizations.organization', verbose_name='المنظمة'),
        ),
    ]
