# Generated by Django 4.2.10 on 2024-03-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='الرقم')),
                ('damage_percentage', models.CharField(blank=True, max_length=50, null=True, verbose_name='النسبة المئوية')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Text')),
                ('design_shape', models.CharField(blank=True, max_length=255, null=True, verbose_name='Design Shape')),
            ],
            options={
                'verbose_name': 'Card Main',
                'verbose_name_plural': 'Card Main',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='الرقم')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='LastUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Last Updated',
                'verbose_name_plural': 'Last Updated',
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True, verbose_name='المفتاح')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم')),
                ('relief', models.FloatField(verbose_name='الإغاثة')),
                ('recovery', models.FloatField(verbose_name='التعافي')),
                ('development', models.FloatField(verbose_name='التنمية')),
                ('cards', models.ManyToManyField(related_name='sector_cards', to='main.cards', verbose_name='Sector Cards')),
            ],
            options={
                'verbose_name': 'القطاع',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='SubSectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True, verbose_name='المفتاح')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='الرقم')),
                ('damage_percentage', models.CharField(blank=True, max_length=50, null=True, verbose_name='النسبة المئوية')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Text')),
                ('design_shape', models.CharField(blank=True, max_length=255, null=True, verbose_name='Design Shape')),
                ('main_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_sector', to='main.sectors')),
            ],
            options={
                'verbose_name': 'Sub Sectors',
                'verbose_name_plural': 'Sub Sectors',
            },
        ),
        migrations.AddField(
            model_name='cards',
            name='card_details',
            field=models.ManyToManyField(related_name='subsectors_cards', to='main.subsectors', verbose_name='Sub Sectors'),
        ),
    ]
