# Generated by Django 4.2.10 on 2024-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectors',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='sector_cards', to='main.cards', verbose_name='Sector Cards'),
        ),
    ]
