# Generated by Django 4.2.10 on 2024-03-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subsectors_damage_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsectors',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم'),
        ),
    ]
