# Generated by Django 4.2.10 on 2024-03-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_subsectors_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(blank=True, max_length=200, null=True, verbose_name='news')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='SummaryTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief', models.FloatField(verbose_name='الإغاثة')),
                ('recovery', models.FloatField(verbose_name='التعافي')),
                ('development', models.FloatField(verbose_name='التنمية')),
                ('total', models.FloatField(verbose_name='الإجمالي')),
            ],
            options={
                'verbose_name': 'Total Value',
                'verbose_name_plural': 'Total Value',
            },
        ),
        migrations.RemoveField(
            model_name='sectors',
            name='cards',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
