# Generated by Django 4.2.10 on 2024-03-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news_summarytotal_remove_sectors_cards_delete_cards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Hero',
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero', 'verbose_name_plural': 'Hero'},
        ),
    ]
