# Generated by Django 4.2.10 on 2024-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_items_hero_alter_hero_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectors',
            options={'verbose_name': 'القطاع', 'verbose_name_plural': 'القطاعات'},
        ),
        migrations.AlterField(
            model_name='sectors',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم'),
        ),
    ]
