# Generated by Django 4.2.10 on 2024-03-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sectors_options_alter_sectors_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='hero',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='hero',
            name='name_ind',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='hero',
            name='name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='news'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='news'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_ind',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='news'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='news'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='name_ind',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='design_shape_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Design Shape'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='design_shape_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Design Shape'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='design_shape_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Design Shape'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='design_shape_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Design Shape'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='name_ind',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='text_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='text_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='subsectors',
            name='text_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text'),
        ),
    ]
