# Generated by Django 4.2.10 on 2024-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_hero_name_ar_hero_name_en_hero_name_ind_hero_name_tr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'البند', 'verbose_name_plural': 'البند'},
        ),
        migrations.AlterModelOptions(
            name='lastupdated',
            options={'verbose_name': 'تاريخ التحديث', 'verbose_name_plural': 'تاريخ التحديث'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'الاخبار', 'verbose_name_plural': 'الاخبار'},
        ),
        migrations.AlterModelOptions(
            name='subsectors',
            options={'verbose_name': ' القطاعات الصفحة الرئيسة', 'verbose_name_plural': ' القطاعات الصفحة الرئيسة'},
        ),
        migrations.AlterModelOptions(
            name='summarytotal',
            options={'verbose_name': ' الإجمالي الصفحة الرئيسة', 'verbose_name_plural': ' الإجمالي الصفحة الرئيسة'},
        ),
        migrations.AlterField(
            model_name='lastupdated',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='lastupdated',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='الوقت'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الخبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الخبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الخبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_ind',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الخبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الخبر'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='design_shape',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شكل التصميم'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='design_shape_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شكل التصميم'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='design_shape_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شكل التصميم'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='design_shape_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شكل التصميم'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='design_shape_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شكل التصميم'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='النص'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='text_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='النص'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='النص'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='text_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='النص'),
        ),
        migrations.AlterField(
            model_name='subsectors',
            name='text_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='النص'),
        ),
    ]
