# Generated by Django 4.2.10 on 2024-05-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_hero_options_alter_lastupdated_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='days_of_genocide',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Days of genocide'),
        ),
    ]
