# Generated by Django 4.2.10 on 2024-03-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updatedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': 'ملف الشيت', 'verbose_name_plural': 'ملف الشيت'},
        ),
    ]
