# Generated by Django 4.2.10 on 2024-02-23 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('damage', models.CharField(max_length=255)),
                ('sub_sector', models.CharField(max_length=255)),
                ('subclassification', models.CharField(max_length=255)),
                ('target_number', models.FloatField()),
                ('total_estimation', models.FloatField()),
                ('action_type', models.CharField(max_length=255)),
                ('action_value', models.FloatField()),
                ('total', models.FloatField()),
                ('finished', models.FloatField()),
                ('finished_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChildAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('target_number', models.FloatField()),
                ('total_estimation', models.FloatField()),
                ('action_type', models.CharField(max_length=255)),
                ('action_value', models.FloatField()),
                ('total', models.FloatField()),
                ('finished', models.FloatField()),
                ('finished_percentage', models.FloatField()),
                ('parent_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard_api.action')),
                ('tags', models.ManyToManyField(related_name='child_actions_tags', to='dashboard_api.tag')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_action', to='dashboard_api.sector'),
        ),
        migrations.AddField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(related_name='actions_tags', to='dashboard_api.tag'),
        ),
    ]
