# Generated by Django 4.2.10 on 2024-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='finished',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='finished_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='finished',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='finished_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
