# Generated by Django 4.2.10 on 2024-02-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0002_alter_action_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='action_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
