# Generated by Django 4.2.10 on 2024-02-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0004_sector_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='slug',
        ),
    ]
