# Generated by Django 4.2.10 on 2024-02-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0005_remove_sector_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief', models.FloatField()),
                ('recovery', models.FloatField()),
                ('development', models.FloatField()),
                ('total', models.FloatField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_summary', to='dashboard_api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('damage_summary', models.CharField(max_length=255)),
                ('sub_sector', models.CharField(max_length=255)),
                ('scope_of_intervention', models.TextField(max_length=600)),
                ('relief', models.FloatField()),
                ('recovery', models.FloatField()),
                ('development', models.FloatField()),
                ('total', models.FloatField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_cost', to='dashboard_api.sector')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_cost', to='dashboard_api.summary')),
            ],
        ),
    ]
