# Generated by Django 4.2.10 on 2024-02-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0006_summary_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='summary',
        ),
        migrations.AddField(
            model_name='summary',
            name='cost',
            field=models.ManyToManyField(blank=True, null=True, related_name='cost_summary', to='dashboard_api.costs'),
        ),
    ]
