# Generated by Django 4.2.10 on 2024-02-26 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0007_remove_costs_summary_summary_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_code', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='dashboard_api.card')),
            ],
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_classification', models.CharField(blank=True, max_length=255, null=True)),
                ('damage_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('damage', models.CharField(blank=True, max_length=255, null=True)),
                ('damage_value_type', models.CharField(blank=True, max_length=50, null=True)),
                ('damage_value_number', models.CharField(blank=True, max_length=50, null=True)),
                ('damage_value_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dashboard_api.chart')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='damage_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='dashboard_api.damagereport'),
        ),
    ]
