# Generated by Django 4.2.10 on 2024-02-29 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0008_card_chart_damagereport_chartdata_card_damage_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='chart',
            options={'verbose_name': 'Chart', 'verbose_name_plural': 'Charts'},
        ),
        migrations.AlterModelOptions(
            name='chartdata',
            options={'verbose_name': 'Chart Data', 'verbose_name_plural': 'Chart Data'},
        ),
        migrations.AlterModelOptions(
            name='childaction',
            options={'verbose_name': 'Child Action', 'verbose_name_plural': 'Child Actions'},
        ),
        migrations.AlterModelOptions(
            name='costs',
            options={'verbose_name': 'Cost', 'verbose_name_plural': 'Costs'},
        ),
        migrations.AlterModelOptions(
            name='damagereport',
            options={'verbose_name': 'Damage Report', 'verbose_name_plural': 'Damage Reports'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Summary', 'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(max_length=255, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Action Value'),
        ),
        migrations.AlterField(
            model_name='action',
            name='damage',
            field=models.CharField(max_length=255, verbose_name='Damage'),
        ),
        migrations.AlterField(
            model_name='action',
            name='finished',
            field=models.FloatField(blank=True, null=True, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='action',
            name='finished_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Finished Percentage'),
        ),
        migrations.AlterField(
            model_name='action',
            name='key',
            field=models.CharField(max_length=10, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='action',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_action', to='dashboard_api.sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='action',
            name='sub_sector',
            field=models.CharField(max_length=255, verbose_name='Sub-sector'),
        ),
        migrations.AlterField(
            model_name='action',
            name='subclassification',
            field=models.CharField(max_length=255, verbose_name='Sub-classification'),
        ),
        migrations.AlterField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(related_name='actions_tags', to='dashboard_api.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_number',
            field=models.FloatField(verbose_name='Target Number'),
        ),
        migrations.AlterField(
            model_name='action',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='action',
            name='total_estimation',
            field=models.FloatField(verbose_name='Total Estimation'),
        ),
        migrations.AlterField(
            model_name='card',
            name='damage_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='dashboard_api.damagereport', verbose_name='Damage Report'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='dashboard_api.card', verbose_name='Card'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='icon_code',
            field=models.TextField(blank=True, null=True, verbose_name='Icon Code'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dashboard_api.chart', verbose_name='Chart'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='data_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='percentage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='action_type',
            field=models.CharField(max_length=255, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='action_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Action Value'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='finished',
            field=models.FloatField(blank=True, null=True, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='finished_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Finished Percentage'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='key',
            field=models.CharField(max_length=10, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='parent_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard_api.action', verbose_name='Parent Action'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='tags',
            field=models.ManyToManyField(related_name='child_actions_tags', to='dashboard_api.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='target_number',
            field=models.FloatField(verbose_name='Target Number'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='total_estimation',
            field=models.FloatField(verbose_name='Total Estimation'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='damage_summary',
            field=models.CharField(max_length=255, verbose_name='Damage Summary'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='development',
            field=models.FloatField(verbose_name='Development'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='key',
            field=models.CharField(max_length=10, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='recovery',
            field=models.FloatField(verbose_name='Recovery'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='relief',
            field=models.FloatField(verbose_name='Relief'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='scope_of_intervention',
            field=models.TextField(max_length=600, verbose_name='Scope of Intervention'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_cost', to='dashboard_api.sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='sub_sector',
            field=models.CharField(max_length=255, verbose_name='Sub-sector'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='total',
            field=models.FloatField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Damage'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage_sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Damage Sector'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage_value_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Damage Value Number'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage_value_percentage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Damage Value Percentage'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage_value_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Damage Value Type'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='sub_classification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-classification'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='sub_sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-sector'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='cost',
            field=models.ManyToManyField(blank=True, null=True, related_name='cost_summary', to='dashboard_api.costs', verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='development',
            field=models.FloatField(verbose_name='Development'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='recovery',
            field=models.FloatField(verbose_name='Recovery'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='relief',
            field=models.FloatField(verbose_name='Relief'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_summary', to='dashboard_api.sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total',
            field=models.FloatField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
