# Generated by Django 4.2.10 on 2024-03-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0009_alter_action_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'التدخل', 'verbose_name_plural': 'التدخلات'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'بطاقة', 'verbose_name_plural': 'بطاقات'},
        ),
        migrations.AlterModelOptions(
            name='chart',
            options={'verbose_name': 'الرسم البياني', 'verbose_name_plural': 'الرسومات البيانيه'},
        ),
        migrations.AlterModelOptions(
            name='chartdata',
            options={'verbose_name': 'بيانات الرسم البياني', 'verbose_name_plural': 'بيانات الرسم البياني'},
        ),
        migrations.AlterModelOptions(
            name='childaction',
            options={'verbose_name': 'التدخل الفرعي', 'verbose_name_plural': ' التدخلات الفرعية'},
        ),
        migrations.AlterModelOptions(
            name='costs',
            options={'verbose_name': 'ملخص الأضرار', 'verbose_name_plural': 'ملخص الأضرار'},
        ),
        migrations.AlterModelOptions(
            name='damagereport',
            options={'verbose_name': 'حصر الاضرار', 'verbose_name_plural': 'حصر الاضرار'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'القطاع', 'verbose_name_plural': 'القطاعات'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'ملخص', 'verbose_name_plural': 'ملخصات'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'الوسم', 'verbose_name_plural': 'الوسوم'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(max_length=255, verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_value',
            field=models.FloatField(blank=True, null=True, verbose_name='قيمة الإجراء'),
        ),
        migrations.AlterField(
            model_name='action',
            name='damage',
            field=models.CharField(max_length=255, verbose_name='الضرر'),
        ),
        migrations.AlterField(
            model_name='action',
            name='finished',
            field=models.FloatField(blank=True, null=True, verbose_name='تم الإنجاز'),
        ),
        migrations.AlterField(
            model_name='action',
            name='finished_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الإنجاز'),
        ),
        migrations.AlterField(
            model_name='action',
            name='key',
            field=models.CharField(max_length=10, verbose_name='رقم'),
        ),
        migrations.AlterField(
            model_name='action',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_action', to='dashboard_api.sector', verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='action',
            name='sub_sector',
            field=models.CharField(max_length=255, verbose_name='القطاع الفرعي'),
        ),
        migrations.AlterField(
            model_name='action',
            name='subclassification',
            field=models.CharField(max_length=255, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AlterField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(related_name='actions_tags', to='dashboard_api.tag', verbose_name='الوسوم'),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_number',
            field=models.FloatField(verbose_name='العدد المستهدف'),
        ),
        migrations.AlterField(
            model_name='action',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='action',
            name='total_estimation',
            field=models.FloatField(verbose_name='التقدير الإجمالي'),
        ),
        migrations.AlterField(
            model_name='card',
            name='damage_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='dashboard_api.damagereport', verbose_name='حصر الاضرار'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='dashboard_api.card', verbose_name='بطاقة'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='icon_code',
            field=models.TextField(blank=True, null=True, verbose_name='كود الأيقونة'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dashboard_api.chart', verbose_name='الرسم البياني'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='data_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع البيانات'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='الرقم'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='percentage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النسبة المئوية'),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='action_type',
            field=models.CharField(max_length=255, verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='action_value',
            field=models.FloatField(blank=True, null=True, verbose_name='قيمة الإجراء'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='finished',
            field=models.FloatField(blank=True, null=True, verbose_name='تم الإنجاز'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='finished_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='نسبة الإنجاز'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='key',
            field=models.CharField(max_length=10, verbose_name='رقم'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='parent_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard_api.action', verbose_name='التدخلات الاساسية'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='tags',
            field=models.ManyToManyField(related_name='child_actions_tags', to='dashboard_api.tag', verbose_name='الوسوم'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='target_number',
            field=models.FloatField(verbose_name='العدد المستهدف'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='childaction',
            name='total_estimation',
            field=models.FloatField(verbose_name='التقدير الإجمالي'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='damage_summary',
            field=models.CharField(max_length=255, verbose_name='ملخص الأضرار'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='development',
            field=models.FloatField(verbose_name='التنمية'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='key',
            field=models.CharField(max_length=10, verbose_name='رقم'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='recovery',
            field=models.FloatField(verbose_name='التعافي'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='relief',
            field=models.FloatField(verbose_name='الإغاثة'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='scope_of_intervention',
            field=models.TextField(max_length=600, verbose_name='نطاق التدخل'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_cost', to='dashboard_api.sector', verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='sub_sector',
            field=models.CharField(max_length=255, verbose_name='القطاع الفرعي'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='total',
            field=models.FloatField(verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage_sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قطاع الضرر'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage_value_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' قيمة الضرر'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage_value_percentage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النسبة المئوية لقيمة الضرر'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='damage_value_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع قيمة الضرر'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='sub_classification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='sub_sector',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='cost',
            field=models.ManyToManyField(blank=True, null=True, related_name='cost_summary', to='dashboard_api.costs', verbose_name='ملخص الأضرار'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='development',
            field=models.FloatField(verbose_name='التنمية'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='recovery',
            field=models.FloatField(verbose_name='التعافي'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='relief',
            field=models.FloatField(verbose_name='الإغاثة'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_summary', to='dashboard_api.sector', verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total',
            field=models.FloatField(verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='الاسم'),
        ),
    ]
