# Generated by Django 4.2.10 on 2024-03-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0010_alter_action_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='icon')),
                ('main_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text')),
                ('main_subtext', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtext')),
                ('main_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم')),
            ],
            options={
                'verbose_name': 'Card Detail',
                'verbose_name_plural': 'Card Detail',
            },
        ),
        migrations.CreateModel(
            name='CardMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='الضرر')),
                ('route', models.CharField(blank=True, max_length=100, null=True, verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Card Main',
                'verbose_name_plural': 'Card Main',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='icon')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='الرقم')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text')),
                ('textsm', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text sm')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='LastUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Last Updated',
                'verbose_name_plural': 'Last Updated',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(blank=True, max_length=200, null=True, verbose_name='news')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='النسبة المئوية')),
                ('total', models.CharField(blank=True, max_length=50, null=True, verbose_name='الإجمالي')),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress',
            },
        ),
        migrations.CreateModel(
            name='SecondaryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='النسبة المئوية')),
                ('total', models.CharField(blank=True, max_length=50, null=True, verbose_name='الإجمالي')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.progress', verbose_name='Progress')),
            ],
            options={
                'verbose_name': 'Secondary Progress',
                'verbose_name_plural': 'Secondary Progress',
            },
        ),
        migrations.CreateModel(
            name='HeroDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='icon')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='number')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Text')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.hero', verbose_name='Hero')),
            ],
            options={
                'verbose_name': 'Hero Detail',
                'verbose_name_plural': 'Hero Detail',
            },
        ),
        migrations.CreateModel(
            name='CardDetailSecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=50, null=True, verbose_name='img')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='الرقم')),
                ('numberText', models.CharField(blank=True, max_length=100, null=True, verbose_name='Number Text')),
                ('card_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_detail', to='dashboard_api.carddetail', verbose_name='Card Detail')),
            ],
            options={
                'verbose_name': 'Card Detail Secondary',
                'verbose_name_plural': 'Card Detail Secondary',
            },
        ),
        migrations.AddField(
            model_name='carddetail',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_api.cardmain', verbose_name='بطاقة'),
        ),
    ]
