# Generated by Django 4.2.10 on 2024-03-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0011_carddetail_cardmain_hero_lastupdated_news_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetail',
            name='card',
        ),
        migrations.RemoveField(
            model_name='carddetailsecondary',
            name='card_detail',
        ),
        migrations.RemoveField(
            model_name='herodetail',
            name='hero',
        ),
        migrations.DeleteModel(
            name='LastUpdated',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='secondaryprogress',
            name='progress',
        ),
        migrations.DeleteModel(
            name='CardDetail',
        ),
        migrations.DeleteModel(
            name='CardDetailSecondary',
        ),
        migrations.DeleteModel(
            name='CardMain',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.DeleteModel(
            name='HeroDetail',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='SecondaryProgress',
        ),
    ]
