# Generated by Django 4.2.10 on 2024-03-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0012_remove_carddetail_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='نوع الإجراء'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_type_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نوع الإجراء'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_type_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='نوع الإجراء'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_type_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='نوع الإجراء'),
        ),
        migrations.AddField(
            model_name='action',
            name='damage_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='action',
            name='damage_en',
            field=models.CharField(max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='action',
            name='damage_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='action',
            name='damage_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='action',
            name='sub_sector_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='action',
            name='sub_sector_en',
            field=models.CharField(max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='action',
            name='sub_sector_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='action',
            name='sub_sector_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='action',
            name='subclassification_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AddField(
            model_name='action',
            name='subclassification_en',
            field=models.CharField(max_length=255, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AddField(
            model_name='action',
            name='subclassification_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AddField(
            model_name='action',
            name='subclassification_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='chart',
            name='icon_code_ar',
            field=models.TextField(blank=True, null=True, verbose_name='كود الأيقونة'),
        ),
        migrations.AddField(
            model_name='chart',
            name='icon_code_en',
            field=models.TextField(blank=True, null=True, verbose_name='كود الأيقونة'),
        ),
        migrations.AddField(
            model_name='chart',
            name='icon_code_ind',
            field=models.TextField(blank=True, null=True, verbose_name='كود الأيقونة'),
        ),
        migrations.AddField(
            model_name='chart',
            name='icon_code_tr',
            field=models.TextField(blank=True, null=True, verbose_name='كود الأيقونة'),
        ),
        migrations.AddField(
            model_name='chart',
            name='type_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='chart',
            name='type_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='chart',
            name='type_ind',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='chart',
            name='type_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='data_type_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع البيانات'),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='data_type_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع البيانات'),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='data_type_ind',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع البيانات'),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='data_type_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع البيانات'),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='name_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='name_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='childaction',
            name='action_type_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='نوع الإجراء'),
        ),
        migrations.AddField(
            model_name='childaction',
            name='action_type_en',
            field=models.CharField(max_length=255, null=True, verbose_name='نوع الإجراء'),
        ),
        migrations.AddField(
            model_name='childaction',
            name='action_type_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='نوع الإجراء'),
        ),
        migrations.AddField(
            model_name='childaction',
            name='action_type_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='نوع الإجراء'),
        ),
        migrations.AddField(
            model_name='costs',
            name='damage_summary_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='ملخص الأضرار'),
        ),
        migrations.AddField(
            model_name='costs',
            name='damage_summary_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ملخص الأضرار'),
        ),
        migrations.AddField(
            model_name='costs',
            name='damage_summary_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='ملخص الأضرار'),
        ),
        migrations.AddField(
            model_name='costs',
            name='damage_summary_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='ملخص الأضرار'),
        ),
        migrations.AddField(
            model_name='costs',
            name='scope_of_intervention_ar',
            field=models.TextField(max_length=600, null=True, verbose_name='نطاق التدخل'),
        ),
        migrations.AddField(
            model_name='costs',
            name='scope_of_intervention_en',
            field=models.TextField(max_length=600, null=True, verbose_name='نطاق التدخل'),
        ),
        migrations.AddField(
            model_name='costs',
            name='scope_of_intervention_ind',
            field=models.TextField(max_length=600, null=True, verbose_name='نطاق التدخل'),
        ),
        migrations.AddField(
            model_name='costs',
            name='scope_of_intervention_tr',
            field=models.TextField(max_length=600, null=True, verbose_name='نطاق التدخل'),
        ),
        migrations.AddField(
            model_name='costs',
            name='sub_sector_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='costs',
            name='sub_sector_en',
            field=models.CharField(max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='costs',
            name='sub_sector_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='costs',
            name='sub_sector_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_sector_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قطاع الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_sector_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قطاع الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_sector_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قطاع الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_sector_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قطاع الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_value_type_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع قيمة الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_value_type_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع قيمة الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_value_type_ind',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع قيمة الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='damage_value_type_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع قيمة الضرر'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sector_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sector_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sector_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sector_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sub_classification_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sub_classification_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sub_classification_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sub_classification_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sub_sector_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sub_sector_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sub_sector_ind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='sub_sector_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القطاع الفرعي'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ar',
            field=models.CharField(max_length=20, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ind',
            field=models.CharField(max_length=20, null=True, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_tr',
            field=models.CharField(max_length=20, null=True, verbose_name='الاسم'),
        ),
    ]
