# Generated by Django 4.2.10 on 2024-03-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0013_action_action_type_ar_action_action_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم'),
        ),
    ]
